Traceback (most recent call last):
  File "C:\Users\CICEA\miniconda3\envs\scratch\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CICEA\miniconda3\envs\scratch\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\CICEA\miniconda3\envs\scratch\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\CICEA\miniconda3\envs\scratch\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\CICEA\miniconda3\envs\scratch\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\CICEA\miniconda3\envs\scratch\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\CICEA\miniconda3\envs\scratch\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\CICEA\miniconda3\envs\scratch\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# El siguiente cÃ³digo carga la imagen desde el paquete skimage.io
# Esta sintaxis permite cargar solamente un subpaquete (en este caso `io`) desde una libreria mÃ¡s grande (en este caso skimage)
from skimage import io

# Cargamos la imagen desde el URL
imagen = io.imread('https://i.natgeofe.com/n/548467d8-c5f1-4551-9f58-6817a8d2c45e/NationalGeographic_2572187_square.jpg')
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[23], line 3[0m
[0;32m      1[0m [38;5;66;03m# El siguiente cÃ³digo carga la imagen desde el paquete skimage.io[39;00m
[0;32m      2[0m [38;5;66;03m# Esta sintaxis permite cargar solamente un subpaquete (en este caso `io`) desde una libreria mÃ¡s grande (en este caso skimage)[39;00m
[1;32m----> 3[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mskimage[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m io
[0;32m      5[0m [38;5;66;03m# Cargamos la imagen desde el URL[39;00m
[0;32m      6[0m imagen [38;5;241m=[39m io[38;5;241m.[39mimread([38;5;124m'[39m[38;5;124mhttps://i.natgeofe.com/n/548467d8-c5f1-4551-9f58-6817a8d2c45e/NationalGeographic_2572187_square.jpg[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'skimage'

