Traceback (most recent call last):
  File "/Users/martin/miniconda3/envs/scratch/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/martin/miniconda3/envs/scratch/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/martin/miniconda3/envs/scratch/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/martin/miniconda3/envs/scratch/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/martin/miniconda3/envs/scratch/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/martin/miniconda3/envs/scratch/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/martin/miniconda3/envs/scratch/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
barImg = iio.imread('https://raw.githubusercontent.com/MaestriaCienciasCognitivas/ncc/main/book/static/Practico6_Bar.png')
visualizar_imagen(barImg)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m barImg [38;5;241m=[39m [43miio[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mhttps://raw.githubusercontent.com/MaestriaCienciasCognitivas/ncc/main/book/static/Practico6_Bar.png[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m visualizar_imagen(barImg)

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/site-packages/imageio/v3.py:53[0m, in [0;36mimread[0;34m(uri, index, plugin, extension, format_hint, **kwargs)[0m
[1;32m     50[0m [38;5;28;01mif[39;00m index [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m     51[0m     call_kwargs[[38;5;124m"[39m[38;5;124mindex[39m[38;5;124m"[39m] [38;5;241m=[39m index
[0;32m---> 53[0m [38;5;28;01mwith[39;00m [43mimopen[49m[43m([49m[43muri[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mplugin_kwargs[49m[43m)[49m [38;5;28;01mas[39;00m img_file:
[1;32m     54[0m     [38;5;28;01mreturn[39;00m np[38;5;241m.[39masarray(img_file[38;5;241m.[39mread([38;5;241m*[39m[38;5;241m*[39mcall_kwargs))

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/site-packages/imageio/core/imopen.py:196[0m, in [0;36mimopen[0;34m(uri, io_mode, plugin, extension, format_hint, legacy_mode, **kwargs)[0m
[1;32m    193[0m     [38;5;28;01mcontinue[39;00m
[1;32m    195[0m [38;5;28;01mtry[39;00m:
[0;32m--> 196[0m     plugin_instance [38;5;241m=[39m [43mcandidate_plugin[49m[43m([49m[43mrequest[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    197[0m [38;5;28;01mexcept[39;00m InitializationError:
[1;32m    198[0m     [38;5;66;03m# file extension doesn't match file type[39;00m
[1;32m    199[0m     [38;5;28;01mcontinue[39;00m

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/site-packages/imageio/plugins/pillow.py:104[0m, in [0;36mPillowPlugin.__init__[0;34m(self, request)[0m
[1;32m    102[0m [38;5;28;01mif[39;00m request[38;5;241m.[39mmode[38;5;241m.[39mio_mode [38;5;241m==[39m IOMode[38;5;241m.[39mread:
[1;32m    103[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 104[0m         [38;5;28;01mwith[39;00m Image[38;5;241m.[39mopen([43mrequest[49m[38;5;241;43m.[39;49m[43mget_file[49m[43m([49m[43m)[49m):
[1;32m    105[0m             [38;5;66;03m# Check if it is generally possible to read the image.[39;00m
[1;32m    106[0m             [38;5;66;03m# This will not read any data and merely try to find a[39;00m
[1;32m    107[0m             [38;5;66;03m# compatible pillow plugin (ref: the pillow docs).[39;00m
[1;32m    108[0m             [38;5;28;01mpass[39;00m
[1;32m    109[0m     [38;5;28;01mexcept[39;00m UnidentifiedImageError:

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/site-packages/imageio/core/request.py:514[0m, in [0;36mRequest.get_file[0;34m(self)[0m
[1;32m    512[0m     [38;5;28;01mif[39;00m timeout [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m timeout[38;5;241m.[39misdigit():
[1;32m    513[0m         timeout [38;5;241m=[39m [38;5;241m5[39m
[0;32m--> 514[0m     [38;5;28mself[39m[38;5;241m.[39m_file [38;5;241m=[39m [43murlopen[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m,[49m[43m [49m[43mtimeout[49m[38;5;241;43m=[39;49m[38;5;28;43mfloat[39;49m[43m([49m[43mtimeout[49m[43m)[49m[43m)[49m
[1;32m    515[0m     [38;5;28mself[39m[38;5;241m.[39m_file [38;5;241m=[39m SeekableFileObject([38;5;28mself[39m[38;5;241m.[39m_file)
[1;32m    517[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_file

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/site-packages/imageio/core/util.py:34[0m, in [0;36murlopen[0;34m(*args, **kwargs)[0m
[1;32m     32[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m     33[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mCould not import urlopen.[39m[38;5;124m"[39m)
[0;32m---> 34[0m [38;5;28;01mreturn[39;00m [43murlopen[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/urllib/request.py:216[0m, in [0;36murlopen[0;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[1;32m    214[0m [38;5;28;01melse[39;00m:
[1;32m    215[0m     opener [38;5;241m=[39m _opener
[0;32m--> 216[0m [38;5;28;01mreturn[39;00m [43mopener[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/urllib/request.py:525[0m, in [0;36mOpenerDirector.open[0;34m(self, fullurl, data, timeout)[0m
[1;32m    523[0m [38;5;28;01mfor[39;00m processor [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mprocess_response[38;5;241m.[39mget(protocol, []):
[1;32m    524[0m     meth [38;5;241m=[39m [38;5;28mgetattr[39m(processor, meth_name)
[0;32m--> 525[0m     response [38;5;241m=[39m [43mmeth[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mresponse[49m[43m)[49m
[1;32m    527[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/urllib/request.py:634[0m, in [0;36mHTTPErrorProcessor.http_response[0;34m(self, request, response)[0m
[1;32m    631[0m [38;5;66;03m# According to RFC 2616, "2xx" code indicates that the client's[39;00m
[1;32m    632[0m [38;5;66;03m# request was successfully received, understood, and accepted.[39;00m
[1;32m    633[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([38;5;241m200[39m [38;5;241m<[39m[38;5;241m=[39m code [38;5;241m<[39m [38;5;241m300[39m):
[0;32m--> 634[0m     response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mparent[49m[38;5;241;43m.[39;49m[43merror[49m[43m([49m
[1;32m    635[0m [43m        [49m[38;5;124;43m'[39;49m[38;5;124;43mhttp[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mrequest[49m[43m,[49m[43m [49m[43mresponse[49m[43m,[49m[43m [49m[43mcode[49m[43m,[49m[43m [49m[43mmsg[49m[43m,[49m[43m [49m[43mhdrs[49m[43m)[49m
[1;32m    637[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/urllib/request.py:563[0m, in [0;36mOpenerDirector.error[0;34m(self, proto, *args)[0m
[1;32m    561[0m [38;5;28;01mif[39;00m http_err:
[1;32m    562[0m     args [38;5;241m=[39m ([38;5;28mdict[39m, [38;5;124m'[39m[38;5;124mdefault[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mhttp_error_default[39m[38;5;124m'[39m) [38;5;241m+[39m orig_args
[0;32m--> 563[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_call_chain[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/urllib/request.py:496[0m, in [0;36mOpenerDirector._call_chain[0;34m(self, chain, kind, meth_name, *args)[0m
[1;32m    494[0m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[1;32m    495[0m     func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[0;32m--> 496[0m     result [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[1;32m    497[0m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    498[0m         [38;5;28;01mreturn[39;00m result

File [0;32m~/miniconda3/envs/scratch/lib/python3.10/urllib/request.py:643[0m, in [0;36mHTTPDefaultErrorHandler.http_error_default[0;34m(self, req, fp, code, msg, hdrs)[0m
[1;32m    642[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mhttp_error_default[39m([38;5;28mself[39m, req, fp, code, msg, hdrs):
[0;32m--> 643[0m     [38;5;28;01mraise[39;00m HTTPError(req[38;5;241m.[39mfull_url, code, msg, hdrs, fp)

[0;31mHTTPError[0m: HTTP Error 429: Too Many Requests

